# Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.



In [321]:
list1 = [1,2,3,4,5]
a = np.array(list1)
a

array([1, 2, 3, 4, 5])

In [322]:
np.vander(a,increasing = True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [323]:
np.vander(a)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below i	1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == == Input 10 20 30 40 50 60 70 80 90 100
y1	25 = (10+20+30+40)/4
y2	35 = (20+30+40+50)/4
y3	45 = (30+40+50+60)/4
y4	55 = (40+50+60+70)/4
y5	65 = (50+60+70+80)/4
y6	75 = (60+70+80+90)/4
y7	85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.
 
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.


In [330]:
import numpy as np
dataset = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

def movingavrage(values,window):
    weights = np.repeat(1.0,window)/window
    smas = np.convolve(values,weights,'valid')
    return weights 


movingavrage(dataset,3)

array([0.33333333, 0.33333333, 0.33333333])

# Function obtaining moving average using numpy np.ones

In [338]:
import numpy as np
dataset = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

def movingavrage_npones(values,window):
    weights = np.ones(window)/window
    smas = np.convolve(values,weights,'valid')
    return smas 


movingavrage_npones(dataset,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

# using for loop and enumerate finding the cumulative sum and calculating moving average

In [329]:
import numpy as np
dataset = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
cumsum = [0]
xval = []
moving_aves =[]
for i,x in enumerate(dataset,1):
    cumsum.append(cumsum[i-1]+x)
    if(i>=k):
        moving_ave = (cumsum[i]-cumsum[i-k])/k
        print("y"+str((i+1-k)),str(moving_ave) + "  =  "+ str(cumsum))

y1 5.0  =  [0, 3, 8, 15]
y2 4.666666666666667  =  [0, 3, 8, 15, 17]
y3 5.666666666666667  =  [0, 3, 8, 15, 17, 25]
y4 6.666666666666667  =  [0, 3, 8, 15, 17, 25, 35]
y5 9.666666666666666  =  [0, 3, 8, 15, 17, 25, 35, 46]
y6 28.666666666666668  =  [0, 3, 8, 15, 17, 25, 35, 46, 111]
y7 49.333333333333336  =  [0, 3, 8, 15, 17, 25, 35, 46, 111, 183]
y8 72.66666666666667  =  [0, 3, 8, 15, 17, 25, 35, 46, 111, 183, 264]
y9 84.0  =  [0, 3, 8, 15, 17, 25, 35, 46, 111, 183, 264, 363]
y10 93.33333333333333  =  [0, 3, 8, 15, 17, 25, 35, 46, 111, 183, 264, 363, 463]
y11 116.33333333333333  =  [0, 3, 8, 15, 17, 25, 35, 46, 111, 183, 264, 363, 463, 613]
